### ISSUE TITLE
Error Example

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-custom-pages-extended#1]
I get an error on the profile picture by clicking.
![example_01](https://cloud.githubusercontent.com/assets/3394915/6958806/f625b5fa-d94b-11e4-836f-5ae0ec605f67.png)
![example_02](https://cloud.githubusercontent.com/assets/3394915/6958804/f624ab92-d94b-11e4-929d-989b9649c28d.png)
![example_03](https://cloud.githubusercontent.com/assets/3394915/6958805/f624f89a-d94b-11e4-9867-726d9562ec4f.png)

**Comment by Vatarus** [comment]
Humhub version: 0.11.0-1

**Comment by WASasquatch** [comment]
I'll take a look I haven't tested it on 0.11.0-1 yet. It was written of 0.10.1 :) Thanks for letting me know.

**Comment by WASasquatch** [comment]
It was a typo from a copy/paste. Go ahead and grab a new copy of the code

https://github.com/WASasquatch/humhub-modules-custom-pages-extended/blob/master/docs/example.md

**Comment by Vatarus** [comment]
Well done! Thanks! Good job!
