### ISSUE TITLE
m150413_030602_create_visibility_column Error

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-custom-pages-extended#2]
Hi!

Fix this: 
$this->createColumn('custom_pages_page', 'visibility', 'int(1)');

on this:
$this->**addColumn**('custom_pages_page', 'visibility', 'int(1)');

file: m150413_030602_create_visibility_column

**Comment by WASasquatch** [comment]
Thanks.

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/humhub-modules-custom-pages-extended/commit/245f1e29153972c852f6b625a684a977c86258fd
