### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by jus61** [WASasquatch/humhub-modules-custom-pages-extended#3]
it is possible that they integrate with an editor like CKEditor

**Comment by WASasquatch** [comment]
CKEditor unfortunately has issues with Bootstrap theme and destroys humhub. But I've added the markdown editor for markdown pages. 

I tried both raw CKEditor as my own widget, and it cause some problems, but they were too great to leave implemented. The CKEditor widget EditMe completely destroyed the functionality of the page and reproduced menus everywhere. Lol
