### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [WASasquatch/humhub-modules-custom-pages-extended#7]
I have install this module and have a error:

Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /homepages/12/d576585625/htdocs/protected/modules/custom_pages/models/CustomPage.php on line 193

**Comment by WASasquatch** [comment]
What version of PHP do you have installed? 

Also I made a adjustment to the file that may fix the issue: https://github.com/WASasquatch/humhub-modules-custom-pages-extended/blob/master/models/CustomPage.php
