### ISSUE TITLE
A Few Issues

### ISSUE THREAD

**Issue by Felli** [WASasquatch/humhub-modules-custom-pages-extended#9]
So I really like this module, but I've seen a few problems
1. Widgets display is a little broken.
![](http://i.imgur.com/ZusQsNt.png)
2. The same thing happens on PHP.
3. You're unable to use script for social badges (You can add them but it isn't visible.)
4. After making a custom page this happens
![](http://i.imgur.com/xFoCiKv.png)

**Comment by WASasquatch** [comment]
**_PHP Page / Widget Usage**_
1. The PHP pages run off the eval() functioning, meaning all supplied input needs to be already in PHP Mode. Do not start, or end with <?php ... ?>, instead write as if already in PHP Mode.
2. **_One of the most important things to remember is you are writing PHP in the confines of Yii and HumHub and must write within those standards.**_
3. You can use the object var $user to access user information such as the user display name $user->displayName
4. When using Widget Type Space (Sidebar Widget) you can access the space information with the $space variable. For example to access the space name you would use $space->name

You must use Yii when programming. Custom Pages is also not compatible with latest versions of HumHub.
